# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Reactjs Node Continuous Integration Workflow

on:
  push:
    branches: [ client ]
  pull_request:
    branches: [ client ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Run test suites
      run: npm test

    - name: Build app 
      run: npm run build --if-present
      
      env: 
        CI: false
